In [1]:
import numpy as np

In [2]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [4]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [5]:
arr2 = np.arange(10, 20, 1) # (start, stop, stepsize)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
arr3dim = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
arr3dim

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [7]:
arr3dim * 3

array([[[ 3,  6,  9],
        [ 9, 12, 15]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [9]:
arr2 * 5

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [13]:
arr4 = arr1 * arr1 

In [11]:
arr3dim[1]

array([[5, 6, 7],
       [7, 8, 9]])

In [14]:
arr4.sum()

1400

In [15]:
arr4.var()

108888.88888888888

In [18]:
for x in arr1:
    print(x)

10
20
30


In [19]:
for x in np.nditer(arr3dim):
    print(x)

1
2
3
3
4
5
5
6
7
7
8
9


In [20]:
np.save("new", arr1)

In [21]:
np.load("new.npy")

array([10, 20, 30])

In [22]:
np.savetxt("new.txt", arr1,delimiter=',')

In [23]:
np.loadtxt("new.txt",delimiter=',')

array([10., 20., 30.])